Merge master into work with userlist URL

diff --git a/docker/k666-env b/docker/k666-env
--- a/docker/k666-env
+++ b/docker/k666-env
@@ -8,17 +8,26 @@
 # From: electrum/electrum-env
 # Modified: procrasti@k5-stats.org 13 Aug 2015
 
-PYTHON=python
+PYTHON=python3
 
-if which virtualenv; then
-    if which ${PYTHON}; then
-        if ! [ -e ./env/bin/activate ]; then
-	        virtualenv env -p ${PYTHON}
+export DJANGO_SETTINGS_MODULE="k666.settings"
+export DEFAULT_DATABASE="sqlite3"
+export DEBUG=True
+
+if which ${PYTHON}; then
+    if ! [ -e ./env/bin/activate ]; then
+        if which virtualenv; then
+            virtualenv env -p ${PYTHON}
+        else
+            echo "virtualenv not found, using built in venv"
+            ${PYTHON} -m venv env
         fi
+    fi
 
-        source ./env/bin/activate
-        python setup.py install
-        pip unzip django_messages # We want this gone!
+    source ./env/bin/activate
+    pip install --upgrade 'pip<7' # We want this gone too! We need the latest version of pip that supports unzip.
+    python setup.py install
+    pip unzip django_messages # We want this gone!
 
         # WHY DOESN'T THIS WORK FROM setup.py?
         # pip install django-recaptcha2
@@ -38,16 +47,11 @@ if which virtualenv; then
             ./manage.py createsuperuser
         fi
 
-        export DJANGO_SETTINGS_MODULE="k666.settings"
 
-        ./manage.py runserver "$@"
-        # deactivate
-    else
-        echo "You probably have to install ${PYTHON}"
-        echo "sudo apt-get install python3?"
-    fi
+    ./manage.py runserver "$@"
+    # deactivate
 else
-    echo "You probably have to install virtualenv."
-    echo "sudo apt-get install python-virtualenv?"
+    echo "You probably have to install ${PYTHON}"
+    echo "sudo apt-get install python3?"
 fi
 
